services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - APP_ENV=development
      - LOG_LEVEL=DEBUG
      - DATABASE_TYPE=chroma
      - GRAPH_STORE_URL=bolt://memgraph:7687
    depends_on:
      - chroma
      - memgraph
    networks:
      - knowledge-graph-net
    command: python main.py

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_db:/data  # Mount to Chroma's default data directory
    environment:
      - ALLOW_RESET=true
      - CHROMA_API_IMPL=rest
      - CHROMA_SERVER_HOST=chroma
      - CHROMA_SERVER_HTTP_PORT=8000
    networks:
      - knowledge-graph-net
  
  memgraph:
    image: memgraph/memgraph:2.11.0
    ports:
      - "7687:7687"  # Bolt protocol
      - "7444:7444"  # HTTP for management
    environment:
      - MEMGRAPH_LOG_LEVEL=WARNING
    volumes:
      - memgraph_data:/var/lib/memgraph
    networks:
      - knowledge-graph-net
  
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - app
    networks:
      - knowledge-graph-net

volumes:
  chroma-data:
  memgraph_data:

networks:
  knowledge-graph-net:
    driver: bridge
